### ISSUE TITLE
执行ginana run有问题

### ISSUE THREAD

**Issue by jiangfu204** [griffin702/ginana#1]
执行ginana run 之后命令行提示 No help topic for 'run'，能帮忙看看么

**Comment by griffin702** [comment]
可以加微信联系：griffin702



117976509@qq.com
 
发件人： jiangfu204
发送时间： 2020-06-16 17:31
收件人： griffin702/ginana
抄送： Subscribed
主题： [griffin702/ginana] 执行ginana run有问题 (#1)
执行ginana run 之后命令行提示 No help topic for 'run'，能帮忙看看么
